defaultHelp results/help.txt


fieldWidth 300
fieldHeight 300


defaultCenterX 50.0
defaultCenterY 50.0
defaultSigmaX 5.0
defaultSigmaY 5.0
defaultHeight 10.0


xmin 0
xmax 300
ymin 0
ymax 300
sx_min 2
sx_max 5
sy_min 2
sy_max 5
h_min -30
h_max 30
count_min 200
count_max 201
defaultGAutoMode Fixed 42


defaultGnuplot results/visualizations/Gnuplot.png
defaultPlotMetedata results/visualizations/Metadata.png
defaultPlotKmeans results/visualizations/kmeans.png
defaultPlotGraph results/visualizations/Graph.png
defaultPlotVoronoi results/visualizations/Voronoi.png
defaultPlotDelaunay results/visualizations/Delaunay.png
defaultPlotPath results/visualizations/Path.png
defaultPlot3DPath results/visualizations/Plot3DPath.png

defaultWrite results/visualizations/Write.bmp 
defaultWriteModeImage Full
defaultRead results/visualizations/Read.bmp

save_g config/commands/gaussians.txt


defaultThreshold 130
defaultBinMode All


defaultNoisy 10


defaultKlaster 5
defaultKlasterKern 5


defaultstartPointX 55
defaultstartPointY 295
defaultendPointX 295
defaultendPointY 5
defaultConnectMode All

vehicleRadius 1
maxSideAngle 90.0
maxUpDownAngle 90.0


logFileNameInterface var/logs/log_interface.txt
logFileNameControl var/logs/logcontrol.txt

FiltrationLogLevelInterface OFF
FiltrationLogLevelControl OFF
